### ISSUE TITLE
Integrate redux-offline and redux-persist ?

### ISSUE THREAD

**Issue by Sharlaan** [dleitee/react-fetches#4]
Suggestion: how about adding to the stack [redux-offline](https://github.com/redux-offline/redux-offline) and [redux-persist](https://github.com/rt2zz/redux-persist) ?

**Comment by dleitee** [comment]
hmmm, for while we don't have `redux` implemented here, but we have an idea to add offline support soon.

**Comment by Sharlaan** [comment]
Huh? From main page, i thought half of your lib is based on Redux and co ?

**Comment by dleitee** [comment]
I based just the concept of connect.
