### ISSUE TITLE
Passing parameters to request functions

### ISSUE THREAD

**Issue by david** [dleitee/react-fetches#8]
Hi, thanks for your work on react-fetches. 

I was wondering if there is a way to pass down props from the component to specific requests. For example assuming I have the following `mapRequestToProps`

```es6
const mapRequestToProps = (http => ({
  customer: http.get("/customers", { userId /* <- */ })
});

export connect(mapRequestToProps)(Summary);
```
and I use the `Summary` component as
```jsx
<Summary userId={123} />
```
how can I pass `userId` to the request that will fill in the `customer` prop above?

**Comment by dleitee** [comment]
Hey @david, thank you for this issue.

This feature was a thing that I was thinking at the start of this project, just have forgotten.

I created a version `v1.0.1` where the third parameter of `mapRequestToProps` is the `currentProps`. So you can use this feature right now.

I'm working on a v2.0, so if you have any opinion about this library and wanna to contribute, feel free to comment here #10 .

**Comment by david** [comment]
@dleitee thanks for the quick response, I appreciate it.
